/** Help center search index — generated by check-help-center.sh, loaded at runtime. */

export interface HelpCenterIndex {
  version: number;
  generatedAt: string;
  articleCount: number;
  avgDocLen: number;
  sections: SectionMeta[];
  idf: Record<string, number>;
  articles: ArticleEntry[];
}

export interface SectionMeta {
  slug: string;
  name: string;
  articleCount: number;
  file: string;
}

export interface ArticleEntry {
  id: number;
  title: string;
  section: string;
  sourceUrl: string;
  questions: string[];
  tokens: string[];
  tokenCount: number;
  snippet: string;
}

export interface SearchResult {
  article: ArticleEntry;
  score: number;
  section: SectionMeta;
  matchedTerms: string[];
}

// ── Embedding types ──────────────────────────────────────────────

export interface EmbeddingIndex {
  version: number;
  model: string;
  dimensions: number;
  generatedAt: string;
  articleCount: number;
  embeddings: ArticleEmbedding[];
}

export interface ArticleEmbedding {
  articleId: number;
  vector: number[];
}

export type SearchMode = 'semantic' | 'bm25' | 'hybrid';
